version: '3.8'

services:
  streamlit:
    image: streamlit:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - '8501:8501'  # Map host port 8501 to container port 8501
    networks:
      - streamlit
    restart: unless-stopped

networks:
  streamlit:
